spring.application.name=copa2026

spring.datasource.url=jdbc:postgresql://localhost:5432/bolao_copa_2026
spring.datasource.username=postgres
spring.datasource.password=devbuarque

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true